/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationDTO } from './ApplicationDTO';
import {
    ApplicationDTOFromJSON,
    ApplicationDTOFromJSONTyped,
    ApplicationDTOToJSON,
    ApplicationDTOToJSONTyped,
} from './ApplicationDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ApplicationDTORequestResponse
 */
export interface ApplicationDTORequestResponse {
    /**
     * 
     * @type {ApplicationDTO}
     * @memberof ApplicationDTORequestResponse
     */
    readonly response?: ApplicationDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ApplicationDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ApplicationDTORequestResponse interface.
 */
export function instanceOfApplicationDTORequestResponse(value: object): value is ApplicationDTORequestResponse {
    return true;
}

export function ApplicationDTORequestResponseFromJSON(json: any): ApplicationDTORequestResponse {
    return ApplicationDTORequestResponseFromJSONTyped(json, false);
}

export function ApplicationDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ApplicationDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ApplicationDTORequestResponseToJSON(json: any): ApplicationDTORequestResponse {
    return ApplicationDTORequestResponseToJSONTyped(json, false);
}

export function ApplicationDTORequestResponseToJSONTyped(value?: Omit<ApplicationDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

