/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { ApplicationDTOPagedResponse } from './ApplicationDTOPagedResponse';
import {
    ApplicationDTOPagedResponseFromJSON,
    ApplicationDTOPagedResponseFromJSONTyped,
    ApplicationDTOPagedResponseToJSON,
    ApplicationDTOPagedResponseToJSONTyped,
} from './ApplicationDTOPagedResponse';

/**
 * 
 * @export
 * @interface ApplicationDTOPagedResponseRequestResponse
 */
export interface ApplicationDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ApplicationDTOPagedResponse}
     * @memberof ApplicationDTOPagedResponseRequestResponse
     */
    readonly response?: ApplicationDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ApplicationDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ApplicationDTOPagedResponseRequestResponse interface.
 */
export function instanceOfApplicationDTOPagedResponseRequestResponse(value: object): value is ApplicationDTOPagedResponseRequestResponse {
    return true;
}

export function ApplicationDTOPagedResponseRequestResponseFromJSON(json: any): ApplicationDTOPagedResponseRequestResponse {
    return ApplicationDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ApplicationDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ApplicationDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ApplicationDTOPagedResponseRequestResponseToJSON(json: any): ApplicationDTOPagedResponseRequestResponse {
    return ApplicationDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function ApplicationDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<ApplicationDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

