/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationDTO } from './ApplicationDTO';
import {
    ApplicationDTOFromJSON,
    ApplicationDTOFromJSONTyped,
    ApplicationDTOToJSON,
    ApplicationDTOToJSONTyped,
} from './ApplicationDTO';

/**
 * 
 * @export
 * @interface ApplicationDTOPagedResponse
 */
export interface ApplicationDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ApplicationDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicationDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicationDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<ApplicationDTO>}
     * @memberof ApplicationDTOPagedResponse
     */
    data: Array<ApplicationDTO>;
}

/**
 * Check if a given object implements the ApplicationDTOPagedResponse interface.
 */
export function instanceOfApplicationDTOPagedResponse(value: object): value is ApplicationDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ApplicationDTOPagedResponseFromJSON(json: any): ApplicationDTOPagedResponse {
    return ApplicationDTOPagedResponseFromJSONTyped(json, false);
}

export function ApplicationDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(ApplicationDTOFromJSON)),
    };
}

export function ApplicationDTOPagedResponseToJSON(json: any): ApplicationDTOPagedResponse {
    return ApplicationDTOPagedResponseToJSONTyped(json, false);
}

export function ApplicationDTOPagedResponseToJSONTyped(value?: ApplicationDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(ApplicationDTOToJSON)),
    };
}

