/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApplicationStatusEnum = {
    Pending: 'Pending',
    Accepted: 'Accepted',
    Rejected: 'Rejected'
} as const;
export type ApplicationStatusEnum = typeof ApplicationStatusEnum[keyof typeof ApplicationStatusEnum];


export function instanceOfApplicationStatusEnum(value: any): boolean {
    for (const key in ApplicationStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(ApplicationStatusEnum, key)) {
            if (ApplicationStatusEnum[key as keyof typeof ApplicationStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApplicationStatusEnumFromJSON(json: any): ApplicationStatusEnum {
    return ApplicationStatusEnumFromJSONTyped(json, false);
}

export function ApplicationStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationStatusEnum {
    return json as ApplicationStatusEnum;
}

export function ApplicationStatusEnumToJSON(value?: ApplicationStatusEnum | null): any {
    return value as any;
}

export function ApplicationStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ApplicationStatusEnum {
    return value as ApplicationStatusEnum;
}

