/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationAddDTO
 */
export interface ApplicationAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ApplicationAddDTO
     */
    projectId: string;
}

/**
 * Check if a given object implements the ApplicationAddDTO interface.
 */
export function instanceOfApplicationAddDTO(value: object): value is ApplicationAddDTO {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    return true;
}

export function ApplicationAddDTOFromJSON(json: any): ApplicationAddDTO {
    return ApplicationAddDTOFromJSONTyped(json, false);
}

export function ApplicationAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
    };
}

export function ApplicationAddDTOToJSON(json: any): ApplicationAddDTO {
    return ApplicationAddDTOToJSONTyped(json, false);
}

export function ApplicationAddDTOToJSONTyped(value?: ApplicationAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
    };
}

