/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationStatusEnum } from './ApplicationStatusEnum';
import {
    ApplicationStatusEnumFromJSON,
    ApplicationStatusEnumFromJSONTyped,
    ApplicationStatusEnumToJSON,
    ApplicationStatusEnumToJSONTyped,
} from './ApplicationStatusEnum';

/**
 * 
 * @export
 * @interface ApplicationDTO
 */
export interface ApplicationDTO {
    /**
     * 
     * @type {string}
     * @memberof ApplicationDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationDTO
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationDTO
     */
    projectTitle: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationDTO
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationDTO
     */
    userName: string;
    /**
     * 
     * @type {ApplicationStatusEnum}
     * @memberof ApplicationDTO
     */
    status: ApplicationStatusEnum;
}



/**
 * Check if a given object implements the ApplicationDTO interface.
 */
export function instanceOfApplicationDTO(value: object): value is ApplicationDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('projectTitle' in value) || value['projectTitle'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApplicationDTOFromJSON(json: any): ApplicationDTO {
    return ApplicationDTOFromJSONTyped(json, false);
}

export function ApplicationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'projectTitle': json['projectTitle'],
        'userId': json['userId'],
        'userName': json['userName'],
        'status': ApplicationStatusEnumFromJSON(json['status']),
    };
}

export function ApplicationDTOToJSON(json: any): ApplicationDTO {
    return ApplicationDTOToJSONTyped(json, false);
}

export function ApplicationDTOToJSONTyped(value?: ApplicationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'projectTitle': value['projectTitle'],
        'userId': value['userId'],
        'userName': value['userName'],
        'status': ApplicationStatusEnumToJSON(value['status']),
    };
}

