/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationStatusEnum } from './ApplicationStatusEnum';
import {
    ApplicationStatusEnumFromJSON,
    ApplicationStatusEnumFromJSONTyped,
    ApplicationStatusEnumToJSON,
    ApplicationStatusEnumToJSONTyped,
} from './ApplicationStatusEnum';

/**
 * 
 * @export
 * @interface ApplicationUpdateDTO
 */
export interface ApplicationUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ApplicationUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {ApplicationStatusEnum}
     * @memberof ApplicationUpdateDTO
     */
    status: ApplicationStatusEnum;
}



/**
 * Check if a given object implements the ApplicationUpdateDTO interface.
 */
export function instanceOfApplicationUpdateDTO(value: object): value is ApplicationUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApplicationUpdateDTOFromJSON(json: any): ApplicationUpdateDTO {
    return ApplicationUpdateDTOFromJSONTyped(json, false);
}

export function ApplicationUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': ApplicationStatusEnumFromJSON(json['status']),
    };
}

export function ApplicationUpdateDTOToJSON(json: any): ApplicationUpdateDTO {
    return ApplicationUpdateDTOToJSONTyped(json, false);
}

export function ApplicationUpdateDTOToJSONTyped(value?: ApplicationUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ApplicationStatusEnumToJSON(value['status']),
    };
}

