/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationDTOPagedResponse } from './OrganizationDTOPagedResponse';
import {
    OrganizationDTOPagedResponseFromJSON,
    OrganizationDTOPagedResponseFromJSONTyped,
    OrganizationDTOPagedResponseToJSON,
    OrganizationDTOPagedResponseToJSONTyped,
} from './OrganizationDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface OrganizationDTOPagedResponseRequestResponse
 */
export interface OrganizationDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {OrganizationDTOPagedResponse}
     * @memberof OrganizationDTOPagedResponseRequestResponse
     */
    readonly response?: OrganizationDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof OrganizationDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the OrganizationDTOPagedResponseRequestResponse interface.
 */
export function instanceOfOrganizationDTOPagedResponseRequestResponse(value: object): value is OrganizationDTOPagedResponseRequestResponse {
    return true;
}

export function OrganizationDTOPagedResponseRequestResponseFromJSON(json: any): OrganizationDTOPagedResponseRequestResponse {
    return OrganizationDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function OrganizationDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : OrganizationDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function OrganizationDTOPagedResponseRequestResponseToJSON(json: any): OrganizationDTOPagedResponseRequestResponse {
    return OrganizationDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function OrganizationDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<OrganizationDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

