/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { OrganizationDTO } from './OrganizationDTO';
import {
    OrganizationDTOFromJSON,
    OrganizationDTOFromJSONTyped,
    OrganizationDTOToJSON,
    OrganizationDTOToJSONTyped,
} from './OrganizationDTO';

/**
 * 
 * @export
 * @interface OrganizationDTORequestResponse
 */
export interface OrganizationDTORequestResponse {
    /**
     * 
     * @type {OrganizationDTO}
     * @memberof OrganizationDTORequestResponse
     */
    readonly response?: OrganizationDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof OrganizationDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the OrganizationDTORequestResponse interface.
 */
export function instanceOfOrganizationDTORequestResponse(value: object): value is OrganizationDTORequestResponse {
    return true;
}

export function OrganizationDTORequestResponseFromJSON(json: any): OrganizationDTORequestResponse {
    return OrganizationDTORequestResponseFromJSONTyped(json, false);
}

export function OrganizationDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : OrganizationDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function OrganizationDTORequestResponseToJSON(json: any): OrganizationDTORequestResponse {
    return OrganizationDTORequestResponseToJSONTyped(json, false);
}

export function OrganizationDTORequestResponseToJSONTyped(value?: Omit<OrganizationDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

