/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationAddDTO
 */
export interface OrganizationAddDTO {
    /**
     * 
     * @type {string}
     * @memberof OrganizationAddDTO
     */
    name: string;
}

/**
 * Check if a given object implements the OrganizationAddDTO interface.
 */
export function instanceOfOrganizationAddDTO(value: object): value is OrganizationAddDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationAddDTOFromJSON(json: any): OrganizationAddDTO {
    return OrganizationAddDTOFromJSONTyped(json, false);
}

export function OrganizationAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function OrganizationAddDTOToJSON(json: any): OrganizationAddDTO {
    return OrganizationAddDTOToJSONTyped(json, false);
}

export function OrganizationAddDTOToJSONTyped(value?: OrganizationAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

