/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationDTO } from './OrganizationDTO';
import {
    OrganizationDTOFromJSON,
    OrganizationDTOFromJSONTyped,
    OrganizationDTOToJSON,
    OrganizationDTOToJSONTyped,
} from './OrganizationDTO';

/**
 * 
 * @export
 * @interface OrganizationDTOPagedResponse
 */
export interface OrganizationDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof OrganizationDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<OrganizationDTO>}
     * @memberof OrganizationDTOPagedResponse
     */
    data: Array<OrganizationDTO>;
}

/**
 * Check if a given object implements the OrganizationDTOPagedResponse interface.
 */
export function instanceOfOrganizationDTOPagedResponse(value: object): value is OrganizationDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganizationDTOPagedResponseFromJSON(json: any): OrganizationDTOPagedResponse {
    return OrganizationDTOPagedResponseFromJSONTyped(json, false);
}

export function OrganizationDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(OrganizationDTOFromJSON)),
    };
}

export function OrganizationDTOPagedResponseToJSON(json: any): OrganizationDTOPagedResponse {
    return OrganizationDTOPagedResponseToJSONTyped(json, false);
}

export function OrganizationDTOPagedResponseToJSONTyped(value?: OrganizationDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(OrganizationDTOToJSON)),
    };
}

