/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUpdateDTO
 */
export interface OrganizationUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUpdateDTO
     */
    name?: string | null;
}

/**
 * Check if a given object implements the OrganizationUpdateDTO interface.
 */
export function instanceOfOrganizationUpdateDTO(value: object): value is OrganizationUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function OrganizationUpdateDTOFromJSON(json: any): OrganizationUpdateDTO {
    return OrganizationUpdateDTOFromJSONTyped(json, false);
}

export function OrganizationUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OrganizationUpdateDTOToJSON(json: any): OrganizationUpdateDTO {
    return OrganizationUpdateDTOToJSONTyped(json, false);
}

export function OrganizationUpdateDTOToJSONTyped(value?: OrganizationUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

