/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDTO } from './ProjectDTO';
import {
    ProjectDTOFromJSON,
    ProjectDTOFromJSONTyped,
    ProjectDTOToJSON,
    ProjectDTOToJSONTyped,
} from './ProjectDTO';

/**
 * 
 * @export
 * @interface ProjectDTOPagedResponse
 */
export interface ProjectDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<ProjectDTO>}
     * @memberof ProjectDTOPagedResponse
     */
    data: Array<ProjectDTO>;
}

/**
 * Check if a given object implements the ProjectDTOPagedResponse interface.
 */
export function instanceOfProjectDTOPagedResponse(value: object): value is ProjectDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ProjectDTOPagedResponseFromJSON(json: any): ProjectDTOPagedResponse {
    return ProjectDTOPagedResponseFromJSONTyped(json, false);
}

export function ProjectDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(ProjectDTOFromJSON)),
    };
}

export function ProjectDTOPagedResponseToJSON(json: any): ProjectDTOPagedResponse {
    return ProjectDTOPagedResponseToJSONTyped(json, false);
}

export function ProjectDTOPagedResponseToJSONTyped(value?: ProjectDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(ProjectDTOToJSON)),
    };
}

