/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAddDTO
 */
export interface ProjectAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ProjectAddDTO
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectAddDTO
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectAddDTO
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectAddDTO
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ProjectAddDTO
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectAddDTO
     */
    organizationId: string;
}

/**
 * Check if a given object implements the ProjectAddDTO interface.
 */
export function instanceOfProjectAddDTO(value: object): value is ProjectAddDTO {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function ProjectAddDTOFromJSON(json: any): ProjectAddDTO {
    return ProjectAddDTOFromJSONTyped(json, false);
}

export function ProjectAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'location': json['location'],
        'organizationId': json['organizationId'],
    };
}

export function ProjectAddDTOToJSON(json: any): ProjectAddDTO {
    return ProjectAddDTOToJSONTyped(json, false);
}

export function ProjectAddDTOToJSONTyped(value?: ProjectAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'startDate': ((value['startDate']).toISOString()),
        'endDate': ((value['endDate']).toISOString()),
        'location': value['location'],
        'organizationId': value['organizationId'],
    };
}

