/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDTO } from './ProjectDTO';
import {
    ProjectDTOFromJSON,
    ProjectDTOFromJSONTyped,
    ProjectDTOToJSON,
    ProjectDTOToJSONTyped,
} from './ProjectDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ProjectDTORequestResponse
 */
export interface ProjectDTORequestResponse {
    /**
     * 
     * @type {ProjectDTO}
     * @memberof ProjectDTORequestResponse
     */
    readonly response?: ProjectDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProjectDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ProjectDTORequestResponse interface.
 */
export function instanceOfProjectDTORequestResponse(value: object): value is ProjectDTORequestResponse {
    return true;
}

export function ProjectDTORequestResponseFromJSON(json: any): ProjectDTORequestResponse {
    return ProjectDTORequestResponseFromJSONTyped(json, false);
}

export function ProjectDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ProjectDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ProjectDTORequestResponseToJSON(json: any): ProjectDTORequestResponse {
    return ProjectDTORequestResponseToJSONTyped(json, false);
}

export function ProjectDTORequestResponseToJSONTyped(value?: Omit<ProjectDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

