/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDTOPagedResponse } from './ProjectDTOPagedResponse';
import {
    ProjectDTOPagedResponseFromJSON,
    ProjectDTOPagedResponseFromJSONTyped,
    ProjectDTOPagedResponseToJSON,
    ProjectDTOPagedResponseToJSONTyped,
} from './ProjectDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ProjectDTOPagedResponseRequestResponse
 */
export interface ProjectDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ProjectDTOPagedResponse}
     * @memberof ProjectDTOPagedResponseRequestResponse
     */
    readonly response?: ProjectDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProjectDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ProjectDTOPagedResponseRequestResponse interface.
 */
export function instanceOfProjectDTOPagedResponseRequestResponse(value: object): value is ProjectDTOPagedResponseRequestResponse {
    return true;
}

export function ProjectDTOPagedResponseRequestResponseFromJSON(json: any): ProjectDTOPagedResponseRequestResponse {
    return ProjectDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ProjectDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ProjectDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ProjectDTOPagedResponseRequestResponseToJSON(json: any): ProjectDTOPagedResponseRequestResponse {
    return ProjectDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function ProjectDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<ProjectDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

