/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUpdateDTO
 */
export interface ProjectUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    location?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectUpdateDTO
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectUpdateDTO
     */
    endDate?: Date | null;
}

/**
 * Check if a given object implements the ProjectUpdateDTO interface.
 */
export function instanceOfProjectUpdateDTO(value: object): value is ProjectUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ProjectUpdateDTOFromJSON(json: any): ProjectUpdateDTO {
    return ProjectUpdateDTOFromJSONTyped(json, false);
}

export function ProjectUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function ProjectUpdateDTOToJSON(json: any): ProjectUpdateDTO {
    return ProjectUpdateDTOToJSONTyped(json, false);
}

export function ProjectUpdateDTOToJSONTyped(value?: ProjectUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'location': value['location'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

