/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterDTO interface.
 */
export function instanceOfRegisterDTO(value: object): value is RegisterDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterDTOFromJSON(json: any): RegisterDTO {
    return RegisterDTOFromJSONTyped(json, false);
}

export function RegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function RegisterDTOToJSON(json: any): RegisterDTO {
    return RegisterDTOToJSONTyped(json, false);
}

export function RegisterDTOToJSONTyped(value?: RegisterDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

