/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileAddDTO
 */
export interface UserProfileAddDTO {
    /**
     * 
     * @type {string}
     * @memberof UserProfileAddDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileAddDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileAddDTO
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileAddDTO
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileAddDTO
     */
    userId: string;
}

/**
 * Check if a given object implements the UserProfileAddDTO interface.
 */
export function instanceOfUserProfileAddDTO(value: object): value is UserProfileAddDTO {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserProfileAddDTOFromJSON(json: any): UserProfileAddDTO {
    return UserProfileAddDTOFromJSONTyped(json, false);
}

export function UserProfileAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'bio': json['bio'] == null ? undefined : json['bio'],
        'userId': json['userId'],
    };
}

export function UserProfileAddDTOToJSON(json: any): UserProfileAddDTO {
    return UserProfileAddDTOToJSONTyped(json, false);
}

export function UserProfileAddDTOToJSONTyped(value?: UserProfileAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'phoneNumber': value['phoneNumber'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate'] as any).toISOString()),
        'bio': value['bio'],
        'userId': value['userId'],
    };
}

