/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileDTO } from './UserProfileDTO';
import {
    UserProfileDTOFromJSON,
    UserProfileDTOFromJSONTyped,
    UserProfileDTOToJSON,
    UserProfileDTOToJSONTyped,
} from './UserProfileDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface UserProfileDTORequestResponse
 */
export interface UserProfileDTORequestResponse {
    /**
     * 
     * @type {UserProfileDTO}
     * @memberof UserProfileDTORequestResponse
     */
    readonly response?: UserProfileDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserProfileDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the UserProfileDTORequestResponse interface.
 */
export function instanceOfUserProfileDTORequestResponse(value: object): value is UserProfileDTORequestResponse {
    return true;
}

export function UserProfileDTORequestResponseFromJSON(json: any): UserProfileDTORequestResponse {
    return UserProfileDTORequestResponseFromJSONTyped(json, false);
}

export function UserProfileDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : UserProfileDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserProfileDTORequestResponseToJSON(json: any): UserProfileDTORequestResponse {
    return UserProfileDTORequestResponseToJSONTyped(json, false);
}

export function UserProfileDTORequestResponseToJSONTyped(value?: Omit<UserProfileDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

