/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileUpdateDTO } from './UserProfileUpdateDTO';
import {
    UserProfileUpdateDTOFromJSON,
    UserProfileUpdateDTOFromJSONTyped,
    UserProfileUpdateDTOToJSON,
    UserProfileUpdateDTOToJSONTyped,
} from './UserProfileUpdateDTO';

/**
 * 
 * @export
 * @interface UserUpdateDTO
 */
export interface UserUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    password?: string | null;
    /**
     * 
     * @type {UserProfileUpdateDTO}
     * @memberof UserUpdateDTO
     */
    profile?: UserProfileUpdateDTO | null;
}

/**
 * Check if a given object implements the UserUpdateDTO interface.
 */
export function instanceOfUserUpdateDTO(value: object): value is UserUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserUpdateDTOFromJSON(json: any): UserUpdateDTO {
    return UserUpdateDTOFromJSONTyped(json, false);
}

export function UserUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'profile': json['profile'] == null ? undefined : UserProfileUpdateDTOFromJSON(json['profile']),
    };
}

export function UserUpdateDTOToJSON(json: any): UserUpdateDTO {
    return UserUpdateDTOToJSONTyped(json, false);
}

export function UserUpdateDTOToJSONTyped(value?: UserUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
        'profile': UserProfileUpdateDTOToJSON(value['profile']),
    };
}

