/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileDTO
 */
export interface UserProfileDTO {
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDTO
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    userId: string;
}

/**
 * Check if a given object implements the UserProfileDTO interface.
 */
export function instanceOfUserProfileDTO(value: object): value is UserProfileDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserProfileDTOFromJSON(json: any): UserProfileDTO {
    return UserProfileDTOFromJSONTyped(json, false);
}

export function UserProfileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'bio': json['bio'] == null ? undefined : json['bio'],
        'id': json['id'],
        'userId': json['userId'],
    };
}

export function UserProfileDTOToJSON(json: any): UserProfileDTO {
    return UserProfileDTOToJSONTyped(json, false);
}

export function UserProfileDTOToJSONTyped(value?: UserProfileDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'phoneNumber': value['phoneNumber'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate'] as any).toISOString()),
        'bio': value['bio'],
        'id': value['id'],
        'userId': value['userId'],
    };
}

