/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdateDTO
 */
export interface UserProfileUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateDTO
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateDTO
     */
    bio?: string | null;
}

/**
 * Check if a given object implements the UserProfileUpdateDTO interface.
 */
export function instanceOfUserProfileUpdateDTO(value: object): value is UserProfileUpdateDTO {
    return true;
}

export function UserProfileUpdateDTOFromJSON(json: any): UserProfileUpdateDTO {
    return UserProfileUpdateDTOFromJSONTyped(json, false);
}

export function UserProfileUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'bio': json['bio'] == null ? undefined : json['bio'],
    };
}

export function UserProfileUpdateDTOToJSON(json: any): UserProfileUpdateDTO {
    return UserProfileUpdateDTOToJSONTyped(json, false);
}

export function UserProfileUpdateDTOToJSONTyped(value?: UserProfileUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'phoneNumber': value['phoneNumber'],
        'bio': value['bio'],
    };
}

